set -g default-terminal "tmux-256color"
set -sg terminal-overrides "tmux-256color:RGB"

set -g prefix C-a
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g history-limit 10000
set -g renumber-windows on
set -g focus-events on
set -g mouse on
set -g escape-time 0

set -g pane-base-index 1
set -g pane-border-lines simple
set -g pane-border-style fg=black,bright
set -g pane-active-border-style "fg=blue bold"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -l "20%" -c "#{pane_current_path}"

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

bind g popup -d "#{pane_current_path}" -w 90% -h 90% -E "lazygit"

set -g status-style "bg=default"
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-left ""
set -g status-right ""
set -g window-status-current-style "fg=blue bold"
