unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set -g escape-time 10

bind r source-file ~/.tmux.conf \; display "Config reload!"

set-option -g focus-events on
set-option -a terminal-features 'alacritty:RGB'

bind c new-window -c '#{pane_current_path}'
bind '\' split-window -h -c '#{pane_current_path}' 
bind - split-window -v -c '#{pane_current_path}' 

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
