# remap prefix
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# position
set-option -g status-position bottom

# mouse
set -g mouse on

# index
set -g base-index 1
set -g pane-base-index 1

# split panes using v and h
unbind v
unbind h
unbind '"'
unbind %
bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"

# navigate panes using "h,j,k,l"
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Colors

# pane border
set -g pane-border-style fg='#323437'
set -g pane-active-border-style fg='#949494'

# message text
set -g message-style bg='#1e1e2e',fg='#cdd6f4'

# status line
set -g status-style bg='#323437',fg='#bdbdbd'
set -g status-interval 1

# status left
# set -g status-left '#[bg=#C9C7CD]#[fg=#161617]#{?client_prefix,#[bg=#EA83A5],}   '
#set -g status-left '#[bg=#161617]#[fg=#C9C7CD]#{?client_prefix,#[fg=#EA83A6],}  󱓟  '
set -g status-left '#[bg=#323437]#[fg=#bdbdbd]#{?client_prefix,#[fg=#eeeeee],}  󱓟  '

# window status
set-window-option -g window-status-style fg='#bdbdbd',bg=default
set-window-option -g window-status-current-style fg='#80a0ff',bg='#323437'

# status right
set-option -g status-right "#[fg=#80a0ff]#S #[fg=#bdbdbd]%a %d %b %I:%M %p"
